import {
	createGameAudioEngine,
	deriveAudioCueEdgeState,
	detectAudioCuesFromEdgeStates,
	type MusicTrackId,
	resolveMusicTrackForSnapshot,
} from "../../../packages/game-audio/src/index";
import {
	createEmptySimulation,
	createFixedStepRunner,
	deserializeLegacyCommanderFile,
	deserializeSaveState,
	type PilotControlState,
	resolveTimingProfile,
	serializeSaveState,
	type TimingProfileId,
} from "../../../packages/game-core/src/index";
import {
	DEFAULT_SCENARIOS,
	expandIantokTokenText,
	getScenarioById,
} from "../../../packages/game-data/src/index";
import { createGamepadInput, createKeyboardInput } from "../../../packages/game-input/src/index";
import {
	createCanvasRenderer,
	renderMissionTextPages,
	type WireframeBlueprint,
} from "../../../packages/game-renderer/src/index";
import "./styles.css";

const SAVE_SLOT_PRIMARY_KEY = "elite.migration.save-slot-primary";
const SAVE_SLOT_BACKUP_KEY = "elite.migration.save-slot-backup";
const AUDIO_SETTINGS_KEY = "elite.migration.audio-settings-v1";
const KEY_BINDINGS_KEY = "elite.migration.key-bindings-v1";
const ACCESSIBILITY_SETTINGS_KEY = "elite.migration.accessibility-settings-v1";
const FIRST_RUN_GUIDE_KEY = "elite.migration.first-run-guide-v1";
const AUTOSAVE_INTERVAL_MS = 15_000;
const DEFAULT_VARIANT_ID = import.meta.env.VITE_DEFAULT_VARIANT_ID || "gma85-ntsc";
const DATA_BASE_PATH = import.meta.env.VITE_DATA_BASE_PATH || "/game-data";
const ENABLE_SERVICE_WORKER = import.meta.env.PROD && import.meta.env.VITE_DISABLE_SW !== "1";
const ENABLE_LEGACY_COMMANDER_IMPORT = import.meta.env.VITE_ENABLE_LEGACY_COMMANDER_IMPORT === "1";
type RuntimeTimingSelection = TimingProfileId | "auto";

interface RuntimeConfig {
	scenarioId: string;
	variantId: string;
	timing: RuntimeTimingSelection;
	seed: number;
	debug: boolean;
}

interface AudioSettings {
	masterVolume: number;
	sfxVolume: number;
	musicVolume: number;
	muted: boolean;
}

interface KeyBindings {
	rollLeft: string;
	rollRight: string;
	pitchUp: string;
	pitchDown: string;
	throttleUp: string;
	throttleDown: string;
	warpToggle: string;
	escapePod: string;
	fireLaser: string;
	missileArm: string;
	missileFire: string;
	ecmToggle: string;
	dockAttempt: string;
	launch: string;
	saveSnapshot: string;
	loadSnapshot: string;
	menuToggle: string;
	pauseToggle: string;
}

interface AccessibilitySettings {
	highContrast: boolean;
	largeText: boolean;
	reducedFlashing: boolean;
	leftHandedTouch: boolean;
}

interface RuntimePerfStats {
	frameSamples: number[];
	sampleLimit: number;
	overBudgetFrames: number;
	lastFps: number;
}

interface DataPackManifestVariant {
	variantId: string;
	wordsTokenCount: number;
	wordsPaddingBytes: number;
	iantokTokenCount: number;
	iantokTrailingPayloadBytes: number;
	shipBlueprintCount: number;
	spriteCount: number;
	fontGlyphCount: number;
	codialsBytes: number;
	comudatBytes: number;
	themeBytes: number;
}

interface DataPackManifest {
	schemaVersion: number;
	generatedAtIso: string;
	sourceRoot: string;
	outputRoot: string;
	variants: DataPackManifestVariant[];
}

interface RuntimeTokenOpcode {
	kind:
		| "char"
		| "control"
		| "jump"
		| "randomRef"
		| "standardRef"
		| "extendedRef"
		| "twoLetter"
		| "raw";
	value: number;
	hex: string;
	text?: string;
	referenceId?: number;
}

interface RuntimeTokenEntry {
	index: number;
	rawBytes: number[];
	decodedBytes: number[];
	opcodes: RuntimeTokenOpcode[];
}

interface RuntimeDataPack {
	schemaVersion: number;
	variantId: string;
	generatedAtIso: string;
	words: {
		tokenCount: number;
		tokenEntries: RuntimeTokenEntry[];
		trailingPaddingBytes: number[];
		sineTable: number[];
		arctanTable: number[];
	};
	iantok: {
		tokenCount: number;
		tokenEntries: RuntimeTokenEntry[];
		trailingPayloadBytes: number[];
	};
	/**
	 * Ship blueprint payload generated by `@elite/game-data`.
	 * We only model fields required by the current renderer phase.
	 */
	ships: {
		blueprints: RuntimeShipBlueprint[];
		defaultFlagsByShip: unknown[];
		killAwardsByShip: unknown[];
	};
	visuals: {
		sprites: {
			spriteCount: number;
		};
		font: {
			glyphCount: number;
		};
		codials: {
			byteLength: number;
		};
	};
	audio: {
		comudat: {
			byteLength: number;
			bytes: number[];
		};
		theme: {
			byteLength: number;
			bytes: number[];
		};
	};
}

/**
 * Runtime ship vertex shape loaded from generated JSON.
 */
interface RuntimeShipVertex {
	x: number;
	y: number;
	z: number;
}

/**
 * Runtime ship edge shape loaded from generated JSON.
 */
interface RuntimeShipEdge {
	vertex1: number;
	vertex2: number;
}

/**
 * Runtime ship blueprint shape loaded from generated JSON.
 */
interface RuntimeShipBlueprint {
	shipId: number;
	shipName: string;
	vertices: RuntimeShipVertex[];
	edges: RuntimeShipEdge[];
}

interface RuntimeDataContext {
	resolvedVariantId: string;
	manifest: DataPackManifest;
	dataPack: RuntimeDataPack;
}

type DockedUiFlow = "status" | "charts" | "inventory" | "market" | "prompts";

interface DeterminismProbeResult {
	hash: string;
	tick: number;
	scenarioId: string;
	seed: number;
}

interface TouchInputSnapshot {
	active: boolean;
	rollAxis: number;
	pitchAxis: number;
	throttleAxis: number;
	warpTogglePressed: boolean;
	escapePodPressed: boolean;
	fireLaserPressed: boolean;
	missileArmTogglePressed: boolean;
	missileFirePressed: boolean;
	ecmTogglePressed: boolean;
	dockAttemptPressed: boolean;
	launchPressed: boolean;
}

interface TouchInputOverlay {
	root: HTMLDivElement;
	snapshot(): TouchInputSnapshot;
	dispose(): void;
}

declare global {
	interface Window {
		__ELITE_DETERMINISM_PROBE__?: () => DeterminismProbeResult;
	}
}

/**
 * Converts runtime JSON blueprints into renderer-ready minimal blueprints.
 *
 * The map is keyed by canonical ship id so simulation ship slots can resolve
 * geometry by `blueprintId` without repeated array scans.
 */
function buildWireframeBlueprintMap(dataPack: RuntimeDataPack): Map<number, WireframeBlueprint> {
	const map = new Map<number, WireframeBlueprint>();
	for (const blueprint of dataPack.ships.blueprints) {
		map.set(blueprint.shipId, {
			shipId: blueprint.shipId,
			vertices: blueprint.vertices.map((vertex) => ({
				x: vertex.x,
				y: vertex.y,
				z: vertex.z,
			})),
			edges: blueprint.edges.map((edge) => ({
				vertex1: edge.vertex1,
				vertex2: edge.vertex2,
			})),
		});
	}
	return map;
}

/**
 * Parse runtime options from query params:
 * - `scenario` selects scenario id.
 * - `variant` selects generated data-pack variant.
 * - `timing` selects `ntsc`, `pal`, or `auto` frame pacing.
 * - `seed` overrides deterministic seed.
 * - `debug=0` hides debug panel.
 */
function getRuntimeConfigFromUrl(url: URL): RuntimeConfig {
	const fallbackScenario = DEFAULT_SCENARIOS[0];
	if (!fallbackScenario) {
		throw new Error("No default scenarios are configured.");
	}

	const scenarioIdFromQuery = url.searchParams.get("scenario") ?? "empty";
	const scenario = getScenarioById(scenarioIdFromQuery) ?? fallbackScenario;
	const variantId = url.searchParams.get("variant") ?? DEFAULT_VARIANT_ID;
	const timingFromQuery = url.searchParams.get("timing");
	const timing: RuntimeTimingSelection =
		timingFromQuery === "pal" || timingFromQuery === "ntsc" ? timingFromQuery : "auto";

	// Keep seed parsing explicit and resilient to malformed URLs.
	const parsedSeed = Number(url.searchParams.get("seed"));
	const seed = Number.isFinite(parsedSeed) ? parsedSeed >>> 0 : scenario.defaultSeed;

	const debug = url.searchParams.get("debug") !== "0";

	return {
		scenarioId: scenario.id,
		variantId,
		timing,
		seed,
		debug,
	};
}

/**
 * Fetches JSON with an explicit status check so data-load failures surface clearly.
 */
async function fetchJson<T>(url: string): Promise<T> {
	const response = await fetch(url);
	if (!response.ok) {
		throw new Error(`Failed to load ${url} (${response.status} ${response.statusText}).`);
	}
	return (await response.json()) as T;
}

/**
 * Loads generated game-data artifacts from static files under `/game-data`.
 * We resolve unknown variants to the first available manifest entry.
 */
async function loadRuntimeData(desiredVariantId: string): Promise<RuntimeDataContext> {
	const manifest = await fetchJson<DataPackManifest>(`${DATA_BASE_PATH}/manifest.json`);
	if (!manifest.variants.length) {
		throw new Error("Generated manifest has no variants.");
	}

	const match =
		manifest.variants.find((variant) => variant.variantId === desiredVariantId) ??
		manifest.variants[0];

	if (!match) {
		throw new Error("Could not resolve a variant from generated manifest.");
	}

	const dataPack = await fetchJson<RuntimeDataPack>(
		`${DATA_BASE_PATH}/${match.variantId}/data-pack.json`,
	);
	return {
		resolvedVariantId: match.variantId,
		manifest,
		dataPack,
	};
}

/**
 * Convert floating values into fixed-width debug strings for stable overlays.
 */
function fixed(value: number, digits = 2): string {
	return value.toFixed(digits).padStart(8, " ");
}

const DEFAULT_KEY_BINDINGS: KeyBindings = {
	rollLeft: "ArrowLeft",
	rollRight: "ArrowRight",
	pitchUp: "ArrowUp",
	pitchDown: "ArrowDown",
	throttleUp: "ShiftLeft",
	throttleDown: "ControlLeft",
	warpToggle: "KeyH",
	escapePod: "KeyE",
	fireLaser: "Space",
	missileArm: "KeyM",
	missileFire: "KeyN",
	ecmToggle: "KeyX",
	dockAttempt: "KeyL",
	launch: "KeyP",
	saveSnapshot: "F6",
	loadSnapshot: "F7",
	menuToggle: "Escape",
	pauseToggle: "KeyP",
};

const KEY_BINDING_FIELDS: ReadonlyArray<{ key: keyof KeyBindings; label: string }> = [
	{ key: "rollLeft", label: "Roll Left" },
	{ key: "rollRight", label: "Roll Right" },
	{ key: "pitchUp", label: "Pitch Up" },
	{ key: "pitchDown", label: "Pitch Down" },
	{ key: "throttleUp", label: "Throttle +" },
	{ key: "throttleDown", label: "Throttle -" },
	{ key: "fireLaser", label: "Fire Laser" },
	{ key: "missileArm", label: "Missile Arm" },
	{ key: "missileFire", label: "Missile Fire" },
	{ key: "ecmToggle", label: "ECM" },
	{ key: "warpToggle", label: "Warp Toggle" },
	{ key: "escapePod", label: "Escape Pod" },
	{ key: "dockAttempt", label: "Dock Attempt" },
	{ key: "launch", label: "Launch" },
	{ key: "saveSnapshot", label: "Save Snapshot" },
	{ key: "loadSnapshot", label: "Load Snapshot" },
	{ key: "menuToggle", label: "Menu Toggle" },
	{ key: "pauseToggle", label: "Pause Toggle" },
];

const DEFAULT_ACCESSIBILITY_SETTINGS: AccessibilitySettings = {
	highContrast: false,
	largeText: false,
	reducedFlashing: false,
	leftHandedTouch: false,
};

function loadKeyBindingsFromLocalStorage(): KeyBindings {
	const payload = window.localStorage.getItem(KEY_BINDINGS_KEY);
	if (!payload) {
		return { ...DEFAULT_KEY_BINDINGS };
	}

	try {
		const parsed = JSON.parse(payload) as Partial<KeyBindings>;
		const merged = { ...DEFAULT_KEY_BINDINGS };
		for (const field of KEY_BINDING_FIELDS) {
			const candidate = parsed[field.key];
			if (typeof candidate === "string" && candidate.length) {
				merged[field.key] = candidate;
			}
		}
		return merged;
	} catch {
		return { ...DEFAULT_KEY_BINDINGS };
	}
}

function saveKeyBindingsToLocalStorage(bindings: KeyBindings): void {
	window.localStorage.setItem(KEY_BINDINGS_KEY, JSON.stringify(bindings));
}

function loadAccessibilitySettingsFromLocalStorage(): AccessibilitySettings {
	const payload = window.localStorage.getItem(ACCESSIBILITY_SETTINGS_KEY);
	if (!payload) {
		return { ...DEFAULT_ACCESSIBILITY_SETTINGS };
	}

	try {
		const parsed = JSON.parse(payload) as Partial<AccessibilitySettings>;
		return {
			highContrast: Boolean(parsed.highContrast),
			largeText: Boolean(parsed.largeText),
			reducedFlashing: Boolean(parsed.reducedFlashing),
			leftHandedTouch: Boolean(parsed.leftHandedTouch),
		};
	} catch {
		return { ...DEFAULT_ACCESSIBILITY_SETTINGS };
	}
}

function saveAccessibilitySettingsToLocalStorage(settings: AccessibilitySettings): void {
	window.localStorage.setItem(ACCESSIBILITY_SETTINGS_KEY, JSON.stringify(settings));
}

function formatKeyCode(code: string): string {
	if (code.startsWith("Key")) {
		return code.slice(3).toUpperCase();
	}
	if (code.startsWith("Digit")) {
		return code.slice(5);
	}
	if (code.startsWith("Arrow")) {
		return code.slice(5).toUpperCase();
	}
	if (code === "Space") {
		return "SPACE";
	}
	return code.toUpperCase();
}

/**
 * Map keyboard snapshot values into simulation pilot controls.
 *
 * Keeping this mapping in one function makes key-to-control behavior explicit
 * and easy to adjust as we expand the input abstraction.
 */
function mapKeyboardSnapshotToPilotControls(
	snapshot: ReturnType<ReturnType<typeof createKeyboardInput>["snapshot"]>,
	bindings: KeyBindings,
): PilotControlState {
	const pressed = new Set(snapshot.pressedKeys);
	const isPressed = (code: string): boolean => {
		if (pressed.has(code)) {
			return true;
		}
		if (code === "ShiftLeft" || code === "ShiftRight") {
			return pressed.has("ShiftLeft") || pressed.has("ShiftRight");
		}
		if (code === "ControlLeft" || code === "ControlRight") {
			return pressed.has("ControlLeft") || pressed.has("ControlRight");
		}
		if (code === "AltLeft" || code === "AltRight") {
			return pressed.has("AltLeft") || pressed.has("AltRight");
		}
		return false;
	};

	return {
		rollAxis: (isPressed(bindings.rollRight) ? 1 : 0) - (isPressed(bindings.rollLeft) ? 1 : 0),
		pitchAxis: (isPressed(bindings.pitchUp) ? 1 : 0) - (isPressed(bindings.pitchDown) ? 1 : 0),
		throttleAxis:
			(isPressed(bindings.throttleUp) ? 1 : 0) - (isPressed(bindings.throttleDown) ? 1 : 0),
		warpTogglePressed: isPressed(bindings.warpToggle),
		escapePodPressed: isPressed(bindings.escapePod),
		fireLaserPressed: isPressed(bindings.fireLaser),
		missileArmTogglePressed: isPressed(bindings.missileArm),
		missileFirePressed: isPressed(bindings.missileFire),
		ecmTogglePressed: isPressed(bindings.ecmToggle),
		dockAttemptPressed: isPressed(bindings.dockAttempt),
		launchPressed: isPressed(bindings.launch),
	};
}

/**
 * Resolve active timing profile for fixed-step scheduling.
 *
 * `auto` mode infers PAL/NTSC from the currently selected variant id.
 */
function resolveActiveTimingProfile(config: RuntimeConfig) {
	return resolveTimingProfile(config.timing, config.variantId);
}

function clamp01(value: number): number {
	return Math.min(1, Math.max(0, value));
}

function createDefaultPilotControls(): PilotControlState {
	return {
		rollAxis: 0,
		pitchAxis: 0,
		throttleAxis: 0,
		warpTogglePressed: false,
		escapePodPressed: false,
		fireLaserPressed: false,
		missileArmTogglePressed: false,
		missileFirePressed: false,
		ecmTogglePressed: false,
		dockAttemptPressed: false,
		launchPressed: false,
	};
}

function fnv1a32(value: string): string {
	let hash = 0x811c9dc5;
	for (let index = 0; index < value.length; index += 1) {
		hash ^= value.charCodeAt(index);
		hash = Math.imul(hash, 0x01000193) >>> 0;
	}
	return hash.toString(16).padStart(8, "0");
}

function runDeterminismProbe(): DeterminismProbeResult {
	const scenarioId = "empty";
	const seed = 0x12345678;
	const stepMs = 16.67;
	const totalFrames = 600;
	const probeSimulation = createEmptySimulation({
		scenarioId,
		seed,
	});
	const controls = createDefaultPilotControls();
	const keyframes = new Map<number, Partial<PilotControlState>>([
		[0, { throttleAxis: 1, rollAxis: 0.3, pitchAxis: 0.1 }],
		[2, { warpTogglePressed: true }],
		[3, { warpTogglePressed: false }],
		[60, { throttleAxis: 0, rollAxis: 0, pitchAxis: 0 }],
		[80, { missileArmTogglePressed: true }],
		[81, { missileArmTogglePressed: false }],
		[110, { fireLaserPressed: true }],
		[160, { fireLaserPressed: false }],
		[200, { ecmTogglePressed: true }],
		[201, { ecmTogglePressed: false }],
		[260, { dockAttemptPressed: true }],
		[261, { dockAttemptPressed: false }],
		[330, { launchPressed: true }],
		[331, { launchPressed: false }],
	]);

	const signatureLines: string[] = [];
	for (let frame = 0; frame < totalFrames; frame += 1) {
		const updates = keyframes.get(frame);
		if (updates) {
			Object.assign(controls, updates);
		}
		probeSimulation.setPilotControls(controls);
		probeSimulation.step(stepMs);

		if ((frame + 1) % 40 === 0 || frame === totalFrames - 1) {
			const snapshot = probeSimulation.snapshot();
			signatureLines.push(
				[
					snapshot.tick,
					snapshot.rngState,
					Math.round(snapshot.playerHeadingDeg * 100),
					Math.round(snapshot.playerSpeed * 100),
					Math.round(snapshot.gameState.flight.stationDistance * 10),
					snapshot.gameState.universe.localBubbleShips.length,
					snapshot.gameState.views.isDocked ? 1 : 0,
					snapshot.gameState.flight.missileCount,
					snapshot.gameState.commander.creditsCenticredits,
				].join("|"),
			);
		}
	}

	const finalSnapshot = probeSimulation.snapshot();
	return {
		hash: fnv1a32(signatureLines.join(";")),
		tick: finalSnapshot.tick,
		scenarioId: finalSnapshot.scenarioId,
		seed,
	};
}

function mapGamepadSnapshotToPilotControls(
	snapshot: ReturnType<ReturnType<typeof createGamepadInput>["snapshot"]>,
): PilotControlState {
	return {
		rollAxis: snapshot.rollAxis,
		pitchAxis: snapshot.pitchAxis,
		throttleAxis: snapshot.throttleAxis,
		warpTogglePressed: snapshot.warpTogglePressed,
		escapePodPressed: snapshot.escapePodPressed,
		fireLaserPressed: snapshot.fireLaserPressed,
		missileArmTogglePressed: snapshot.missileArmTogglePressed,
		missileFirePressed: snapshot.missileFirePressed,
		ecmTogglePressed: snapshot.ecmTogglePressed,
		dockAttemptPressed: snapshot.dockAttemptPressed,
		launchPressed: snapshot.launchPressed,
	};
}

function mapTouchSnapshotToPilotControls(snapshot: TouchInputSnapshot): PilotControlState {
	return {
		rollAxis: snapshot.rollAxis,
		pitchAxis: snapshot.pitchAxis,
		throttleAxis: snapshot.throttleAxis,
		warpTogglePressed: snapshot.warpTogglePressed,
		escapePodPressed: snapshot.escapePodPressed,
		fireLaserPressed: snapshot.fireLaserPressed,
		missileArmTogglePressed: snapshot.missileArmTogglePressed,
		missileFirePressed: snapshot.missileFirePressed,
		ecmTogglePressed: snapshot.ecmTogglePressed,
		dockAttemptPressed: snapshot.dockAttemptPressed,
		launchPressed: snapshot.launchPressed,
	};
}

function mergePilotControls(inputs: readonly PilotControlState[]): PilotControlState {
	const aggregate = createDefaultPilotControls();
	for (const input of inputs) {
		aggregate.rollAxis += input.rollAxis;
		aggregate.pitchAxis += input.pitchAxis;
		aggregate.throttleAxis += input.throttleAxis;
		aggregate.warpTogglePressed ||= input.warpTogglePressed;
		aggregate.escapePodPressed ||= input.escapePodPressed;
		aggregate.fireLaserPressed ||= input.fireLaserPressed;
		aggregate.missileArmTogglePressed ||= input.missileArmTogglePressed;
		aggregate.missileFirePressed ||= input.missileFirePressed;
		aggregate.ecmTogglePressed ||= input.ecmTogglePressed;
		aggregate.dockAttemptPressed ||= input.dockAttemptPressed;
		aggregate.launchPressed ||= input.launchPressed;
	}

	aggregate.rollAxis = Math.min(1, Math.max(-1, aggregate.rollAxis));
	aggregate.pitchAxis = Math.min(1, Math.max(-1, aggregate.pitchAxis));
	aggregate.throttleAxis = Math.min(1, Math.max(-1, aggregate.throttleAxis));
	return aggregate;
}

function createTouchInputOverlay(target: Window): TouchInputOverlay {
	const touchState = createDefaultPilotControls();
	const root = document.createElement("div");
	root.className = "runtime-touch-controls";
	root.setAttribute("aria-label", "Touch controls");

	const movementCluster = document.createElement("div");
	movementCluster.className = "runtime-touch-cluster";
	const actionCluster = document.createElement("div");
	actionCluster.className = "runtime-touch-cluster";

	const releaseAllControls = (): void => {
		touchState.rollAxis = 0;
		touchState.pitchAxis = 0;
		touchState.throttleAxis = 0;
		touchState.warpTogglePressed = false;
		touchState.escapePodPressed = false;
		touchState.fireLaserPressed = false;
		touchState.missileArmTogglePressed = false;
		touchState.missileFirePressed = false;
		touchState.ecmTogglePressed = false;
		touchState.dockAttemptPressed = false;
		touchState.launchPressed = false;
	};

	const bindHoldButton = (
		label: string,
		className: string,
		onDown: () => void,
		onUp: () => void = () => undefined,
	): HTMLButtonElement => {
		const button = document.createElement("button");
		button.className = `runtime-touch-button ${className}`;
		button.type = "button";
		button.textContent = label;

		const press = (event: PointerEvent): void => {
			event.preventDefault();
			button.setPointerCapture(event.pointerId);
			onDown();
		};
		const release = (event: PointerEvent): void => {
			event.preventDefault();
			onUp();
		};

		button.addEventListener("pointerdown", press);
		button.addEventListener("pointerup", release);
		button.addEventListener("pointercancel", release);
		button.addEventListener("lostpointercapture", onUp);
		return button;
	};

	movementCluster.append(
		bindHoldButton(
			"UP",
			"runtime-touch-axis",
			() => {
				touchState.pitchAxis = 1;
			},
			() => {
				touchState.pitchAxis = 0;
			},
		),
		bindHoldButton(
			"DN",
			"runtime-touch-axis",
			() => {
				touchState.pitchAxis = -1;
			},
			() => {
				touchState.pitchAxis = 0;
			},
		),
		bindHoldButton(
			"LT",
			"runtime-touch-axis",
			() => {
				touchState.rollAxis = -1;
			},
			() => {
				touchState.rollAxis = 0;
			},
		),
		bindHoldButton(
			"RT",
			"runtime-touch-axis",
			() => {
				touchState.rollAxis = 1;
			},
			() => {
				touchState.rollAxis = 0;
			},
		),
		bindHoldButton(
			"TH+",
			"runtime-touch-axis",
			() => {
				touchState.throttleAxis = 1;
			},
			() => {
				touchState.throttleAxis = 0;
			},
		),
		bindHoldButton(
			"TH-",
			"runtime-touch-axis",
			() => {
				touchState.throttleAxis = -1;
			},
			() => {
				touchState.throttleAxis = 0;
			},
		),
	);

	actionCluster.append(
		bindHoldButton(
			"FIRE",
			"runtime-touch-action runtime-touch-primary",
			() => {
				touchState.fireLaserPressed = true;
			},
			() => {
				touchState.fireLaserPressed = false;
			},
		),
		bindHoldButton(
			"ARM",
			"runtime-touch-action",
			() => {
				touchState.missileArmTogglePressed = true;
			},
			() => {
				touchState.missileArmTogglePressed = false;
			},
		),
		bindHoldButton(
			"MSL",
			"runtime-touch-action",
			() => {
				touchState.missileFirePressed = true;
			},
			() => {
				touchState.missileFirePressed = false;
			},
		),
		bindHoldButton(
			"ECM",
			"runtime-touch-action",
			() => {
				touchState.ecmTogglePressed = true;
			},
			() => {
				touchState.ecmTogglePressed = false;
			},
		),
		bindHoldButton(
			"WARP",
			"runtime-touch-action",
			() => {
				touchState.warpTogglePressed = true;
			},
			() => {
				touchState.warpTogglePressed = false;
			},
		),
		bindHoldButton(
			"DOCK",
			"runtime-touch-action",
			() => {
				touchState.dockAttemptPressed = true;
			},
			() => {
				touchState.dockAttemptPressed = false;
			},
		),
		bindHoldButton(
			"LCH",
			"runtime-touch-action",
			() => {
				touchState.launchPressed = true;
			},
			() => {
				touchState.launchPressed = false;
			},
		),
		bindHoldButton(
			"ESC",
			"runtime-touch-action",
			() => {
				touchState.escapePodPressed = true;
			},
			() => {
				touchState.escapePodPressed = false;
			},
		),
	);

	root.append(movementCluster, actionCluster);
	target.addEventListener("blur", releaseAllControls);

	return {
		root,
		snapshot(): TouchInputSnapshot {
			return {
				active: Boolean(
					touchState.rollAxis ||
						touchState.pitchAxis ||
						touchState.throttleAxis ||
						touchState.warpTogglePressed ||
						touchState.escapePodPressed ||
						touchState.fireLaserPressed ||
						touchState.missileArmTogglePressed ||
						touchState.missileFirePressed ||
						touchState.ecmTogglePressed ||
						touchState.dockAttemptPressed ||
						touchState.launchPressed,
				),
				rollAxis: touchState.rollAxis,
				pitchAxis: touchState.pitchAxis,
				throttleAxis: touchState.throttleAxis,
				warpTogglePressed: touchState.warpTogglePressed,
				escapePodPressed: touchState.escapePodPressed,
				fireLaserPressed: touchState.fireLaserPressed,
				missileArmTogglePressed: touchState.missileArmTogglePressed,
				missileFirePressed: touchState.missileFirePressed,
				ecmTogglePressed: touchState.ecmTogglePressed,
				dockAttemptPressed: touchState.dockAttemptPressed,
				launchPressed: touchState.launchPressed,
			};
		},
		dispose(): void {
			target.removeEventListener("blur", releaseAllControls);
			releaseAllControls();
			root.remove();
		},
	};
}

function loadAudioSettingsFromLocalStorage(): AudioSettings {
	const fallback: AudioSettings = {
		masterVolume: 0.35,
		sfxVolume: 1,
		musicVolume: 0.65,
		muted: false,
	};

	const payload = window.localStorage.getItem(AUDIO_SETTINGS_KEY);
	if (!payload) {
		return fallback;
	}

	try {
		const parsed = JSON.parse(payload) as Partial<AudioSettings>;
		return {
			masterVolume: clamp01(Number(parsed.masterVolume ?? fallback.masterVolume)),
			sfxVolume: clamp01(Number(parsed.sfxVolume ?? fallback.sfxVolume)),
			musicVolume: clamp01(Number(parsed.musicVolume ?? fallback.musicVolume)),
			muted: Boolean(parsed.muted ?? fallback.muted),
		};
	} catch {
		return fallback;
	}
}

function saveAudioSettingsToLocalStorage(settings: AudioSettings): void {
	window.localStorage.setItem(AUDIO_SETTINGS_KEY, JSON.stringify(settings));
}

const runtimeConfig = getRuntimeConfigFromUrl(new URL(window.location.href));
const audioSettings = loadAudioSettingsFromLocalStorage();
const keyBindings = loadKeyBindingsFromLocalStorage();
const accessibilitySettings = loadAccessibilitySettingsFromLocalStorage();
const activeTimingProfile = resolveActiveTimingProfile(runtimeConfig);
const root = document.querySelector<HTMLDivElement>("#app");

if (!root) {
	throw new Error("Missing #app root element.");
}
const appRoot = root;

// Build a simple panel layout so we can keep debug tools visible during migration.
const layout = document.createElement("main");
layout.className = "runtime-layout";

const canvasPanel = document.createElement("section");
canvasPanel.className = "runtime-canvas-panel";
const canvas = document.createElement("canvas");
canvas.className = "runtime-canvas";
canvasPanel.append(canvas);

const sidebar = document.createElement("aside");
sidebar.className = "runtime-sidebar";

const title = document.createElement("h1");
title.className = "runtime-title";
title.textContent = "Elite Migration Runtime";

const subtitle = document.createElement("p");
subtitle.className = "runtime-subtitle";
subtitle.textContent = "Loading generated variant data pack...";

const dataStatus = document.createElement("p");
dataStatus.className = "runtime-status";
dataStatus.textContent = "data: loading";

const variantField = document.createElement("label");
variantField.className = "runtime-field";
variantField.textContent = "Variant";

const variantSelect = document.createElement("select");
variantSelect.className = "runtime-select";
variantSelect.disabled = true;
variantField.append(variantSelect);

const timingField = document.createElement("label");
timingField.className = "runtime-field";
timingField.textContent = "Timing";

const timingSelect = document.createElement("select");
timingSelect.className = "runtime-select";
timingField.append(timingSelect);

const muteField = document.createElement("label");
muteField.className = "runtime-field";
muteField.textContent = "Audio";

const muteRow = document.createElement("div");
muteRow.className = "runtime-toggle-row";
const muteToggle = document.createElement("input");
muteToggle.className = "runtime-checkbox";
muteToggle.type = "checkbox";
muteToggle.checked = audioSettings.muted;
const muteText = document.createElement("span");
muteText.textContent = "Mute";
muteRow.append(muteToggle, muteText);
muteField.append(muteRow);

const masterVolumeField = document.createElement("label");
masterVolumeField.className = "runtime-field";
masterVolumeField.textContent = "Master Volume";
const masterVolumeRange = document.createElement("input");
masterVolumeRange.className = "runtime-range";
masterVolumeRange.type = "range";
masterVolumeRange.min = "0";
masterVolumeRange.max = "100";
masterVolumeRange.step = "1";
masterVolumeRange.value = String(Math.round(audioSettings.masterVolume * 100));
masterVolumeField.append(masterVolumeRange);

const sfxVolumeField = document.createElement("label");
sfxVolumeField.className = "runtime-field";
sfxVolumeField.textContent = "SFX Volume";
const sfxVolumeRange = document.createElement("input");
sfxVolumeRange.className = "runtime-range";
sfxVolumeRange.type = "range";
sfxVolumeRange.min = "0";
sfxVolumeRange.max = "100";
sfxVolumeRange.step = "1";
sfxVolumeRange.value = String(Math.round(audioSettings.sfxVolume * 100));
sfxVolumeField.append(sfxVolumeRange);

const musicVolumeField = document.createElement("label");
musicVolumeField.className = "runtime-field";
musicVolumeField.textContent = "Music Volume";
const musicVolumeRange = document.createElement("input");
musicVolumeRange.className = "runtime-range";
musicVolumeRange.type = "range";
musicVolumeRange.min = "0";
musicVolumeRange.max = "100";
musicVolumeRange.step = "1";
musicVolumeRange.value = String(Math.round(audioSettings.musicVolume * 100));
musicVolumeField.append(musicVolumeRange);

const accessibilityField = document.createElement("fieldset");
accessibilityField.className = "runtime-fieldset";
const accessibilityLegend = document.createElement("legend");
accessibilityLegend.className = "runtime-fieldset-title";
accessibilityLegend.textContent = "Accessibility";
accessibilityField.append(accessibilityLegend);

const highContrastRow = document.createElement("label");
highContrastRow.className = "runtime-toggle-row";
const highContrastToggle = document.createElement("input");
highContrastToggle.className = "runtime-checkbox";
highContrastToggle.type = "checkbox";
highContrastToggle.checked = accessibilitySettings.highContrast;
const highContrastText = document.createElement("span");
highContrastText.textContent = "High Contrast";
highContrastRow.append(highContrastToggle, highContrastText);

const largeTextRow = document.createElement("label");
largeTextRow.className = "runtime-toggle-row";
const largeTextToggle = document.createElement("input");
largeTextToggle.className = "runtime-checkbox";
largeTextToggle.type = "checkbox";
largeTextToggle.checked = accessibilitySettings.largeText;
const largeTextText = document.createElement("span");
largeTextText.textContent = "Large Text";
largeTextRow.append(largeTextToggle, largeTextText);

const reducedFlashRow = document.createElement("label");
reducedFlashRow.className = "runtime-toggle-row";
const reducedFlashToggle = document.createElement("input");
reducedFlashToggle.className = "runtime-checkbox";
reducedFlashToggle.type = "checkbox";
reducedFlashToggle.checked = accessibilitySettings.reducedFlashing;
const reducedFlashText = document.createElement("span");
reducedFlashText.textContent = "Reduced Flashing";
reducedFlashRow.append(reducedFlashToggle, reducedFlashText);

const leftHandedTouchRow = document.createElement("label");
leftHandedTouchRow.className = "runtime-toggle-row";
const leftHandedTouchToggle = document.createElement("input");
leftHandedTouchToggle.className = "runtime-checkbox";
leftHandedTouchToggle.type = "checkbox";
leftHandedTouchToggle.checked = accessibilitySettings.leftHandedTouch;
const leftHandedTouchText = document.createElement("span");
leftHandedTouchText.textContent = "Left-Handed Touch Layout";
leftHandedTouchRow.append(leftHandedTouchToggle, leftHandedTouchText);

accessibilityField.append(highContrastRow, largeTextRow, reducedFlashRow, leftHandedTouchRow);

const keyBindingsField = document.createElement("fieldset");
keyBindingsField.className = "runtime-fieldset";
const keyBindingsLegend = document.createElement("legend");
keyBindingsLegend.className = "runtime-fieldset-title";
keyBindingsLegend.textContent = "Key Remapping";
const keyBindingsHint = document.createElement("p");
keyBindingsHint.className = "runtime-note";
keyBindingsHint.textContent = "Select an action, then press a key.";
const keyBindingsGrid = document.createElement("div");
keyBindingsGrid.className = "runtime-keybindings-grid";
const keyBindingButtons = new Map<keyof KeyBindings, HTMLButtonElement>();
for (const field of KEY_BINDING_FIELDS) {
	const label = document.createElement("span");
	label.className = "runtime-keybinding-label";
	label.textContent = field.label;
	const button = document.createElement("button");
	button.className = "runtime-keybinding-button";
	button.type = "button";
	button.setAttribute("aria-label", `Bind ${field.label}`);
	button.textContent = formatKeyCode(keyBindings[field.key]);
	keyBindingButtons.set(field.key, button);
	keyBindingsGrid.append(label, button);
}
const keyBindingsResetButton = document.createElement("button");
keyBindingsResetButton.className = "runtime-button";
keyBindingsResetButton.type = "button";
keyBindingsResetButton.textContent = "Reset Key Bindings";
keyBindingsField.append(
	keyBindingsLegend,
	keyBindingsHint,
	keyBindingsGrid,
	keyBindingsResetButton,
);

/**
 * Timing options are fixed and local, so we can populate them eagerly.
 */
for (const timingOption of [
	{ value: "auto", label: "Auto (by variant)" },
	{ value: "ntsc", label: "NTSC (60 Hz)" },
	{ value: "pal", label: "PAL (50 Hz)" },
]) {
	const option = document.createElement("option");
	option.value = timingOption.value;
	option.textContent = timingOption.label;
	option.selected = timingOption.value === runtimeConfig.timing;
	timingSelect.append(option);
}

const actionBar = document.createElement("div");
actionBar.className = "runtime-actions";

const saveButton = document.createElement("button");
saveButton.className = "runtime-button";
saveButton.textContent = "Save Snapshot (F6)";

const loadButton = document.createElement("button");
loadButton.className = "runtime-button";
loadButton.textContent = "Load Snapshot (F7)";

const exportButton = document.createElement("button");
exportButton.className = "runtime-button";
exportButton.textContent = "Export Snapshot";

const importButton = document.createElement("button");
importButton.className = "runtime-button";
importButton.textContent = "Import Snapshot";

const menuButton = document.createElement("button");
menuButton.className = "runtime-button";
menuButton.textContent = "Menu (Esc)";

const pauseButton = document.createElement("button");
pauseButton.className = "runtime-button";
pauseButton.textContent = "Pause";

actionBar.append(saveButton, loadButton, exportButton, importButton, menuButton, pauseButton);

const importSnapshotInput = document.createElement("input");
importSnapshotInput.type = "file";
importSnapshotInput.accept = ".json,.snapshot,application/json,text/plain";
importSnapshotInput.hidden = true;

const debugPanel = document.createElement("pre");
debugPanel.className = "runtime-debug";
debugPanel.hidden = !runtimeConfig.debug;

const dockedUiPanel = document.createElement("section");
dockedUiPanel.className = "runtime-docked-panel";
const dockedUiTitle = document.createElement("h3");
dockedUiTitle.className = "runtime-docked-title";
dockedUiTitle.textContent = "Docked Text Flows";
const dockedUiTabs = document.createElement("div");
dockedUiTabs.className = "runtime-docked-tabs";
const dockedUiContent = document.createElement("pre");
dockedUiContent.className = "runtime-docked-content";
const dockedUiButtons = new Map<DockedUiFlow, HTMLButtonElement>();
for (const flowKey of ["status", "charts", "inventory", "market", "prompts"] as const) {
	const button = document.createElement("button");
	button.className = "runtime-overlay-tab";
	button.type = "button";
	button.textContent = flowKey.toUpperCase();
	dockedUiButtons.set(flowKey, button);
	dockedUiTabs.append(button);
}
dockedUiPanel.append(dockedUiTitle, dockedUiTabs, dockedUiContent);

const overlay = document.createElement("section");
overlay.className = "runtime-overlay";
overlay.hidden = true;

const overlayPanel = document.createElement("div");
overlayPanel.className = "runtime-overlay-panel";

const overlayTitle = document.createElement("h2");
overlayTitle.className = "runtime-overlay-title";
overlayTitle.textContent = "Runtime Menu";

const overlayTabs = document.createElement("div");
overlayTabs.className = "runtime-overlay-tabs";

const settingsTabButton = document.createElement("button");
settingsTabButton.className = "runtime-overlay-tab";
settingsTabButton.type = "button";
settingsTabButton.textContent = "Settings";

const helpTabButton = document.createElement("button");
helpTabButton.className = "runtime-overlay-tab";
helpTabButton.type = "button";
helpTabButton.textContent = "Help";

overlayTabs.append(settingsTabButton, helpTabButton);

const settingsPane = document.createElement("div");
settingsPane.className = "runtime-overlay-pane";

const helpPane = document.createElement("div");
helpPane.className = "runtime-overlay-pane";

const helpText = document.createElement("pre");
helpText.className = "runtime-help-text";
helpText.textContent = [
	"Input Help",
	"",
	"Keyboard",
	"Roll: A/D or Left/Right",
	"Pitch: W/S or Up/Down",
	"Throttle: Shift / Ctrl",
	"Fire Laser: Space",
	"Missile Arm: M",
	"Missile Fire: N",
	"ECM: X",
	"Warp Toggle: H",
	"Escape Pod: E",
	"Dock Attempt: L",
	"Launch: P",
	"",
	"Gamepad (default mapping)",
	"Steer: Left Stick",
	"Throttle: Triggers",
	"Fire: A  Arm: B  Missile: X  ECM: Y",
	"Warp: LB  Dock: RB  Escape: Back  Launch: Start",
	"",
	"Touch",
	"Use on-screen controls in mobile layout.",
	"Keyboard bindings can be remapped in Settings.",
	"Save Snapshot: F6",
	"Load Snapshot: F7",
	"Export/Import: sidebar buttons",
	"Menu: Esc",
	"Pause: P (keyboard)",
].join("\n");
helpPane.append(helpText);

const overlayActions = document.createElement("div");
overlayActions.className = "runtime-overlay-actions";

const resumeButton = document.createElement("button");
resumeButton.className = "runtime-button";
resumeButton.type = "button";
resumeButton.textContent = "Resume";

const closeButton = document.createElement("button");
closeButton.className = "runtime-button";
closeButton.type = "button";
closeButton.textContent = "Close";

overlayActions.append(resumeButton, closeButton);

const onboardingCard = document.createElement("section");
onboardingCard.className = "runtime-onboarding";

const onboardingTitle = document.createElement("h3");
onboardingTitle.className = "runtime-onboarding-title";
onboardingTitle.textContent = "Quick Start";

const onboardingText = document.createElement("p");
onboardingText.className = "runtime-onboarding-text";
onboardingText.textContent =
	"Use Arrow keys to steer, Shift/Ctrl throttle, Space to fire, M/N for missiles, X for ECM, and Esc for menu.";

const onboardingDoneButton = document.createElement("button");
onboardingDoneButton.className = "runtime-button";
onboardingDoneButton.type = "button";
onboardingDoneButton.textContent = "Got It";

onboardingCard.append(onboardingTitle, onboardingText, onboardingDoneButton);
settingsPane.append(onboardingCard);
overlayPanel.append(overlayTitle, overlayTabs, settingsPane, helpPane, overlayActions);
overlay.append(overlayPanel);

sidebar.append(
	title,
	subtitle,
	dataStatus,
	variantField,
	timingField,
	actionBar,
	importSnapshotInput,
	dockedUiPanel,
	debugPanel,
);
settingsPane.append(
	muteField,
	masterVolumeField,
	sfxVolumeField,
	musicVolumeField,
	accessibilityField,
	keyBindingsField,
);
layout.append(canvasPanel, sidebar);
root.append(layout);
root.append(overlay);
const touchInput = createTouchInputOverlay(window);
canvasPanel.append(touchInput.root);

const simulation = createEmptySimulation({
	scenarioId: runtimeConfig.scenarioId,
	seed: runtimeConfig.seed,
});
const runner = createFixedStepRunner({
	simulation,
	stepMs: activeTimingProfile.stepMs,
	maxCatchUpSteps: activeTimingProfile.maxCatchUpSteps,
});
window.__ELITE_DETERMINISM_PROBE__ = runDeterminismProbe;

// Mutable blueprint map hydrated from generated data-pack JSON.
// The renderer reads through this resolver every frame so it can start rendering
// wireframes immediately after data load, without recreating renderer instance.
let wireframeBlueprintMap = new Map<number, WireframeBlueprint>();

const renderer = createCanvasRenderer({
	canvas,
	wireframeScene: {
		resolveBlueprintById(blueprintId: number): WireframeBlueprint | null {
			return wireframeBlueprintMap.get(blueprintId) ?? null;
		},
		modelScale: 5.5,
		nearPlaneZ: 140,
	},
});
const keyboard = createKeyboardInput(window);
const gamepad = createGamepadInput(window);
const audio = createGameAudioEngine({
	initialVolume: audioSettings.masterVolume,
	initialSfxVolume: audioSettings.sfxVolume,
	initialMusicVolume: audioSettings.musicVolume,
	initialMuted: audioSettings.muted,
});
let runtimeDataContext: RuntimeDataContext | null = null;
let runtimeDataError: string | null = null;
let previousAudioState = deriveAudioCueEdgeState(simulation.snapshot());
let lastExplosionCueMs = -Infinity;
let activeMusicTrackId: MusicTrackId | null = null;
let menuOpen = false;
let paused = false;
let pauseFrameNowMs: number | null = null;
let activeOverlayTab: "settings" | "help" = "settings";
let onboardingAcknowledged = window.localStorage.getItem(FIRST_RUN_GUIDE_KEY) === "1";
let saveStatusMessage = "save: idle";
let lastAutosaveMs = 0;
let tokenPreviewText = "-";
let missionPreviewPages: string[] = ["-"];
let activeDockedFlow: DockedUiFlow = "status";
let serviceWorkerStatusMessage = ENABLE_SERVICE_WORKER
	? "sw: pending registration"
	: "sw: disabled";
const perfStats: RuntimePerfStats = {
	frameSamples: [],
	sampleLimit: 120,
	overBudgetFrames: 0,
	lastFps: 0,
};
let listeningForBinding: keyof KeyBindings | null = null;

function applyAccessibilitySettings(settings: AccessibilitySettings): void {
	appRoot.classList.toggle("runtime-accessibility-large", settings.largeText);
	appRoot.classList.toggle("runtime-accessibility-high-contrast", settings.highContrast);
	appRoot.classList.toggle("runtime-accessibility-reduced-flash", settings.reducedFlashing);
	appRoot.classList.toggle("runtime-touch-left-handed", settings.leftHandedTouch);
}

function updateDockedUiButtons(): void {
	for (const [flowKey, button] of dockedUiButtons.entries()) {
		button.dataset.active = flowKey === activeDockedFlow ? "true" : "false";
	}
}

for (const [flowKey, button] of dockedUiButtons.entries()) {
	button.addEventListener("click", () => {
		activeDockedFlow = flowKey;
		updateDockedUiButtons();
	});
}
updateDockedUiButtons();

function formatDockedUiContent(
	flow: DockedUiFlow,
	snapshot: ReturnType<typeof simulation.snapshot>,
): string {
	switch (flow) {
		case "status":
			return [
				"COMMANDER STATUS",
				`Credits (cc): ${snapshot.gameState.commander.creditsCenticredits}`,
				`Fuel (tenths): ${snapshot.gameState.commander.fuelTenths}`,
				`Legal Status: ${snapshot.gameState.commander.legalStatus}`,
				`Combat Rank Pts: ${snapshot.gameState.commander.combatRankPoints}`,
			].join("\n");
		case "charts":
			return [
				"CHARTS",
				`Galaxy #: ${snapshot.gameState.universe.galaxyNumber}`,
				`Current Seed: ${snapshot.gameState.universe.currentSystemSeed.join("/")}`,
				`Target Seed: ${snapshot.gameState.universe.targetSystemSeed.join("/")}`,
				`Variant: ${runtimeDataContext?.resolvedVariantId ?? "-"}`,
			].join("\n");
		case "inventory":
			return [
				"INVENTORY",
				`Missiles: ${snapshot.gameState.flight.missileCount}`,
				`Missile Armed: ${snapshot.gameState.flight.missileArmed}`,
				`Energy: ${snapshot.gameState.flight.energy.toFixed(1)}`,
				`Forward Shield: ${snapshot.gameState.flight.forwardShield.toFixed(1)}`,
				`Aft Shield: ${snapshot.gameState.flight.aftShield.toFixed(1)}`,
			].join("\n");
		case "market": {
			const seed = snapshot.rngState >>> 0;
			const commodity = (name: string, bias: number) =>
				`${name.padEnd(10, " ")} ${(((seed >>> bias) % 97) + 3).toString().padStart(3, " ")} cr`;
			return [
				"MARKET",
				commodity("Food", 3),
				commodity("Textiles", 5),
				commodity("Ore", 7),
				commodity("Alloys", 11),
				commodity("Computers", 13),
			].join("\n");
		}
		case "prompts":
			return [
				"PROMPTS",
				"[L]aunch from station",
				"[D]ock request when in-space",
				"[M]/[N] missile controls",
				"[F6]/[F7] save/load",
				"[Esc] menu",
			].join("\n");
	}
}

function applyAudioSettings(settings: AudioSettings): void {
	audio.setMasterVolume(settings.masterVolume);
	audio.setSfxVolume(settings.sfxVolume);
	audio.setMusicVolume(settings.musicVolume);
	audio.setMuted(settings.muted);
}

applyAudioSettings(audioSettings);
applyAccessibilitySettings(accessibilitySettings);

function updateOverlayTabUi(): void {
	const settingsActive = activeOverlayTab === "settings";
	settingsPane.hidden = !settingsActive;
	helpPane.hidden = settingsActive;
	settingsTabButton.dataset.active = settingsActive ? "true" : "false";
	helpTabButton.dataset.active = settingsActive ? "false" : "true";
}

function openMenu(tab: "settings" | "help" = "settings"): void {
	activeOverlayTab = tab;
	updateOverlayTabUi();
	menuOpen = true;
	overlay.hidden = false;
}

function closeMenu(): void {
	menuOpen = false;
	overlay.hidden = true;
}

function setPaused(nextPaused: boolean): void {
	paused = nextPaused;
	pauseButton.textContent = paused ? "Resume" : "Pause";
	if (paused) {
		pauseFrameNowMs = performance.now();
		openMenu("settings");
	} else {
		pauseFrameNowMs = null;
		closeMenu();
	}
}

updateOverlayTabUi();
onboardingCard.hidden = onboardingAcknowledged;

async function unlockAudioAfterGesture(): Promise<void> {
	await audio.unlock();
	window.removeEventListener("pointerdown", unlockAudioAfterGesture);
	window.removeEventListener("keydown", unlockAudioAfterGesture);
	window.removeEventListener("touchstart", unlockAudioAfterGesture);
}

window.addEventListener("pointerdown", unlockAudioAfterGesture);
window.addEventListener("keydown", unlockAudioAfterGesture);
window.addEventListener("touchstart", unlockAudioAfterGesture);

muteToggle.addEventListener("change", () => {
	audioSettings.muted = muteToggle.checked;
	audio.setMuted(audioSettings.muted);
	saveAudioSettingsToLocalStorage(audioSettings);
});

masterVolumeRange.addEventListener("input", () => {
	audioSettings.masterVolume = Number(masterVolumeRange.value) / 100;
	audio.setMasterVolume(audioSettings.masterVolume);
	saveAudioSettingsToLocalStorage(audioSettings);
});

sfxVolumeRange.addEventListener("input", () => {
	audioSettings.sfxVolume = Number(sfxVolumeRange.value) / 100;
	audio.setSfxVolume(audioSettings.sfxVolume);
	saveAudioSettingsToLocalStorage(audioSettings);
});

musicVolumeRange.addEventListener("input", () => {
	audioSettings.musicVolume = Number(musicVolumeRange.value) / 100;
	audio.setMusicVolume(audioSettings.musicVolume);
	saveAudioSettingsToLocalStorage(audioSettings);
});

function refreshKeyBindingButtons(): void {
	for (const field of KEY_BINDING_FIELDS) {
		const button = keyBindingButtons.get(field.key);
		if (!button) {
			continue;
		}
		const isActiveCapture = listeningForBinding === field.key;
		button.textContent = isActiveCapture ? "Press Key..." : formatKeyCode(keyBindings[field.key]);
		button.dataset.capture = isActiveCapture ? "true" : "false";
	}
}

for (const field of KEY_BINDING_FIELDS) {
	const button = keyBindingButtons.get(field.key);
	if (!button) {
		continue;
	}
	button.addEventListener("click", () => {
		listeningForBinding = field.key;
		refreshKeyBindingButtons();
	});
}

keyBindingsResetButton.addEventListener("click", () => {
	Object.assign(keyBindings, DEFAULT_KEY_BINDINGS);
	saveKeyBindingsToLocalStorage(keyBindings);
	listeningForBinding = null;
	refreshKeyBindingButtons();
});

refreshKeyBindingButtons();

highContrastToggle.addEventListener("change", () => {
	accessibilitySettings.highContrast = highContrastToggle.checked;
	applyAccessibilitySettings(accessibilitySettings);
	saveAccessibilitySettingsToLocalStorage(accessibilitySettings);
});

largeTextToggle.addEventListener("change", () => {
	accessibilitySettings.largeText = largeTextToggle.checked;
	applyAccessibilitySettings(accessibilitySettings);
	saveAccessibilitySettingsToLocalStorage(accessibilitySettings);
});

reducedFlashToggle.addEventListener("change", () => {
	accessibilitySettings.reducedFlashing = reducedFlashToggle.checked;
	applyAccessibilitySettings(accessibilitySettings);
	saveAccessibilitySettingsToLocalStorage(accessibilitySettings);
});

leftHandedTouchToggle.addEventListener("change", () => {
	accessibilitySettings.leftHandedTouch = leftHandedTouchToggle.checked;
	applyAccessibilitySettings(accessibilitySettings);
	saveAccessibilitySettingsToLocalStorage(accessibilitySettings);
});

settingsTabButton.addEventListener("click", () => {
	activeOverlayTab = "settings";
	updateOverlayTabUi();
});

helpTabButton.addEventListener("click", () => {
	activeOverlayTab = "help";
	updateOverlayTabUi();
});

menuButton.addEventListener("click", () => {
	if (menuOpen) {
		closeMenu();
		return;
	}
	openMenu("settings");
});

pauseButton.addEventListener("click", () => {
	setPaused(!paused);
});

resumeButton.addEventListener("click", () => {
	setPaused(false);
});

closeButton.addEventListener("click", () => {
	closeMenu();
});

onboardingDoneButton.addEventListener("click", () => {
	onboardingAcknowledged = true;
	onboardingCard.hidden = true;
	window.localStorage.setItem(FIRST_RUN_GUIDE_KEY, "1");
	closeMenu();
});

if (!onboardingAcknowledged) {
	openMenu("help");
}

if (ENABLE_SERVICE_WORKER && "serviceWorker" in navigator) {
	window.addEventListener("load", () => {
		navigator.serviceWorker
			.register("/sw.js")
			.then(() => {
				serviceWorkerStatusMessage = "sw: registered";
			})
			.catch((error: unknown) => {
				const reason = error instanceof Error ? error.message : String(error);
				serviceWorkerStatusMessage = `sw: registration failed (${reason})`;
			});
	});
}

function syncMusicTrack(snapshot: ReturnType<typeof simulation.snapshot>): void {
	const nextTrackId = resolveMusicTrackForSnapshot(snapshot);
	if (nextTrackId === activeMusicTrackId) {
		return;
	}
	if (nextTrackId === null) {
		audio.stopMusic();
		activeMusicTrackId = null;
		return;
	}
	audio.playMusic(nextTrackId);
	activeMusicTrackId = nextTrackId;
}

/**
 * Resize canvas to panel bounds and account for browser DPI.
 * This keeps rendering crisp on both desktop and high-density screens.
 */
function resizeCanvasToPanel(): void {
	const bounds = canvasPanel.getBoundingClientRect();
	const pixelRatio = Math.min(window.devicePixelRatio || 1, 2);
	renderer.resize(bounds.width, bounds.height, pixelRatio);
}

window.addEventListener("resize", resizeCanvasToPanel);
resizeCanvasToPanel();

function saveSnapshotToLocalStorage(isAutosave = false): void {
	try {
		const payload = serializeSaveState(simulation.snapshot());
		const previousPrimary = window.localStorage.getItem(SAVE_SLOT_PRIMARY_KEY);
		if (previousPrimary) {
			window.localStorage.setItem(SAVE_SLOT_BACKUP_KEY, previousPrimary);
		}
		window.localStorage.setItem(SAVE_SLOT_PRIMARY_KEY, payload);
		saveStatusMessage = isAutosave
			? "save: autosaved primary+backup"
			: "save: wrote primary+backup";
	} catch (error: unknown) {
		saveStatusMessage = `save: failed (${error instanceof Error ? error.message : String(error)})`;
	}
}

function tryRestoreSnapshotPayload(raw: string): boolean {
	try {
		const envelope = deserializeSaveState(raw);
		simulation.restore(envelope.snapshot);
		return true;
	} catch {
		return false;
	}
}

function loadSnapshotFromLocalStorage(): void {
	const primaryPayload = window.localStorage.getItem(SAVE_SLOT_PRIMARY_KEY);
	const backupPayload = window.localStorage.getItem(SAVE_SLOT_BACKUP_KEY);

	if (!primaryPayload && !backupPayload) {
		saveStatusMessage = "save: no snapshot in storage";
		return;
	}

	if (primaryPayload && tryRestoreSnapshotPayload(primaryPayload)) {
		saveStatusMessage = "save: restored primary snapshot";
		return;
	}

	if (backupPayload && tryRestoreSnapshotPayload(backupPayload)) {
		saveStatusMessage = "save: restored backup snapshot (primary invalid)";
		return;
	}

	saveStatusMessage = "save: both primary and backup are invalid";
}

function exportSnapshotToFile(): void {
	try {
		const payload = serializeSaveState(simulation.snapshot());
		const blob = new Blob([payload], { type: "application/json" });
		const url = URL.createObjectURL(blob);
		const anchor = document.createElement("a");
		const timestamp = new Date().toISOString().replace(/[:.]/g, "-");
		anchor.href = url;
		anchor.download = `elite-migration-snapshot-${timestamp}.json`;
		anchor.click();
		URL.revokeObjectURL(url);
		saveStatusMessage = "save: snapshot exported";
	} catch (error: unknown) {
		saveStatusMessage = `save: export failed (${error instanceof Error ? error.message : String(error)})`;
	}
}

async function importSnapshotFromFile(file: File): Promise<void> {
	const bytes = new Uint8Array(await file.arrayBuffer());
	const decoder = new TextDecoder();
	const payload = decoder.decode(bytes);

	try {
		const envelope = deserializeSaveState(payload);
		simulation.restore(envelope.snapshot);
		const serialized = serializeSaveState(simulation.snapshot());
		window.localStorage.setItem(SAVE_SLOT_BACKUP_KEY, serialized);
		window.localStorage.setItem(SAVE_SLOT_PRIMARY_KEY, serialized);
		saveStatusMessage = "save: imported snapshot and updated storage";
		return;
	} catch {
		// Fall through to optional legacy importer.
	}

	if (!ENABLE_LEGACY_COMMANDER_IMPORT) {
		saveStatusMessage = "save: import failed (invalid snapshot format)";
		return;
	}

	try {
		const legacy = deserializeLegacyCommanderFile(bytes);
		const nextSnapshot = simulation.snapshot();
		nextSnapshot.gameState.commander.creditsCenticredits = legacy.commander.creditsCenticredits;
		nextSnapshot.gameState.commander.fuelTenths = legacy.commander.fuelTenths;
		nextSnapshot.gameState.commander.legalStatus = legacy.commander.legalStatus;
		nextSnapshot.gameState.commander.combatRankPoints = legacy.commander.combatRankPoints;
		nextSnapshot.gameState.flight.missileCount = legacy.flight.missileCount;
		simulation.restore(nextSnapshot);

		const serialized = serializeSaveState(simulation.snapshot());
		window.localStorage.setItem(SAVE_SLOT_BACKUP_KEY, serialized);
		window.localStorage.setItem(SAVE_SLOT_PRIMARY_KEY, serialized);
		saveStatusMessage = `save: imported legacy commander (${legacy.sourceFormat})`;
	} catch (error: unknown) {
		saveStatusMessage = `save: import failed (${error instanceof Error ? error.message : String(error)})`;
	}
}

saveButton.addEventListener("click", () => {
	saveSnapshotToLocalStorage();
});
loadButton.addEventListener("click", loadSnapshotFromLocalStorage);
exportButton.addEventListener("click", exportSnapshotToFile);
importButton.addEventListener("click", () => {
	importSnapshotInput.click();
});
importSnapshotInput.addEventListener("change", async () => {
	const file = importSnapshotInput.files?.[0];
	if (!file) {
		return;
	}
	await importSnapshotFromFile(file);
	importSnapshotInput.value = "";
});

/**
 * Rebuild one URL search param then reload page.
 *
 * Full reload keeps bootstrap logic simple while startup/runtime configuration
 * remains URL-driven in this migration stage.
 */
function reloadWithUrlParam(name: string, value: string): void {
	const url = new URL(window.location.href);
	url.searchParams.set(name, value);
	window.location.href = url.toString();
}

variantSelect.addEventListener("change", () => {
	const selectedVariantId = variantSelect.value;
	if (!selectedVariantId) {
		return;
	}
	reloadWithUrlParam("variant", selectedVariantId);
});

timingSelect.addEventListener("change", () => {
	const selectedTiming = timingSelect.value;
	if (selectedTiming !== "auto" && selectedTiming !== "ntsc" && selectedTiming !== "pal") {
		return;
	}
	reloadWithUrlParam("timing", selectedTiming);
});

window.addEventListener("keydown", (event) => {
	if (listeningForBinding) {
		event.preventDefault();
		if (event.code === "Escape") {
			listeningForBinding = null;
			refreshKeyBindingButtons();
			return;
		}
		keyBindings[listeningForBinding] = event.code;
		saveKeyBindingsToLocalStorage(keyBindings);
		listeningForBinding = null;
		refreshKeyBindingButtons();
		return;
	}

	if (event.code === keyBindings.saveSnapshot) {
		event.preventDefault();
		saveSnapshotToLocalStorage();
	}
	if (event.code === keyBindings.loadSnapshot) {
		event.preventDefault();
		loadSnapshotFromLocalStorage();
	}
	if (event.code === keyBindings.menuToggle) {
		event.preventDefault();
		if (menuOpen) {
			closeMenu();
		} else {
			openMenu("settings");
		}
	}
	if (event.code === keyBindings.pauseToggle) {
		event.preventDefault();
		setPaused(!paused);
	}
});

/**
 * Bootstraps generated data loading and wires variant-selection UI.
 * The app can continue running with fallback simulation even if loading fails.
 */
async function initializeRuntimeDataUi(): Promise<void> {
	try {
		runtimeDataContext = await loadRuntimeData(runtimeConfig.variantId);
		runtimeDataError = null;

		// Rebuild renderer blueprint map from the newly loaded variant pack.
		wireframeBlueprintMap = buildWireframeBlueprintMap(runtimeDataContext.dataPack);
		audio.loadMusicData({
			titleBytes: runtimeDataContext.dataPack.audio.theme.bytes,
			dockingBytes: runtimeDataContext.dataPack.audio.comudat.bytes,
		});
		tokenPreviewText = expandIantokTokenText(
			0,
			{
				words: runtimeDataContext.dataPack.words,
				iantok: runtimeDataContext.dataPack.iantok,
			},
			{
				maxDepth: 4,
				maxOutputLength: 160,
			},
		)
			.replace(/\s+/g, " ")
			.trim()
			.slice(0, 60);
		const missionSeed = [
			expandIantokTokenText(
				0,
				{
					words: runtimeDataContext.dataPack.words,
					iantok: runtimeDataContext.dataPack.iantok,
				},
				{
					maxDepth: 3,
					maxOutputLength: 96,
				},
			),
			"<PAUSE>",
			expandIantokTokenText(
				1,
				{
					words: runtimeDataContext.dataPack.words,
					iantok: runtimeDataContext.dataPack.iantok,
				},
				{
					maxDepth: 3,
					maxOutputLength: 96,
				},
			),
		].join(" ");
		missionPreviewPages = renderMissionTextPages(missionSeed, {
			lineWidth: 28,
			maxLinesPerPage: 6,
		}).map(
			(page, index) => `P${index + 1}${page.pausedAfter ? "*" : " "} ${page.lines.join(" / ")}`,
		);
		syncMusicTrack(simulation.snapshot());

		variantSelect.replaceChildren();
		for (const variant of runtimeDataContext.manifest.variants) {
			const option = document.createElement("option");
			option.value = variant.variantId;
			option.textContent = `${variant.variantId} (${variant.shipBlueprintCount} ships)`;
			if (variant.variantId === runtimeDataContext.resolvedVariantId) {
				option.selected = true;
			}
			variantSelect.append(option);
		}

		variantSelect.disabled = false;
		subtitle.textContent = `Phase M5 runtime: deterministic loop + generated data packs + wireframe projection/clipping (${activeTimingProfile.label}).`;
		dataStatus.textContent = `data: loaded ${runtimeDataContext.resolvedVariantId}`;
	} catch (error: unknown) {
		runtimeDataContext = null;
		runtimeDataError = error instanceof Error ? error.message : String(error);
		wireframeBlueprintMap = new Map<number, WireframeBlueprint>();
		audio.stopMusic();
		activeMusicTrackId = null;
		tokenPreviewText = "-";
		missionPreviewPages = ["-"];

		variantSelect.replaceChildren();
		const fallback = document.createElement("option");
		fallback.value = runtimeConfig.variantId;
		fallback.textContent = `${runtimeConfig.variantId} (unavailable)`;
		fallback.selected = true;
		variantSelect.append(fallback);
		variantSelect.disabled = true;

		subtitle.textContent = `Phase M3 runtime: data-pack load failed, running with simulation fallback (${activeTimingProfile.label}).`;
		dataStatus.textContent = "data: unavailable";
	}
}

void initializeRuntimeDataUi();

/**
 * Render debug text from runtime state. This is intentionally verbose in M2
 * to speed up migration diagnostics before real HUD systems are ported.
 */
function updateDebugPanel(
	nowMs: number,
	frameElapsedMs: number,
	simulatedSteps: number,
	wasClamped: boolean,
): void {
	if (debugPanel.hidden) {
		return;
	}

	const simSnapshot = simulation.snapshot();
	const inputSnapshot = keyboard.snapshot();
	const gamepadSnapshot = gamepad.snapshot();
	const touchSnapshot = touchInput.snapshot();

	const variantSummary =
		runtimeDataContext?.manifest.variants.find(
			(variant) => variant.variantId === runtimeDataContext?.resolvedVariantId,
		) ?? null;

	debugPanel.textContent = [
		`time.nowMs         ${fixed(nowMs, 1)}`,
		`frame.elapsedMs    ${fixed(frameElapsedMs, 2)}`,
		`frame.steps        ${String(simulatedSteps).padStart(8, " ")}`,
		`frame.clamped      ${String(wasClamped).padStart(8, " ")}`,
		`frame.fps          ${fixed(perfStats.lastFps, 1)}`,
		`frame.overBudget   ${String(perfStats.overBudgetFrames).padStart(8, " ")}`,
		`save.status       ${saveStatusMessage}`,
		`sw.status         ${serviceWorkerStatusMessage}`,
		`sim.tick           ${String(simSnapshot.tick).padStart(8, " ")}`,
		`sim.simulatedMs    ${fixed(simSnapshot.simulatedMs, 2)}`,
		`sim.headingDeg     ${fixed(simSnapshot.playerHeadingDeg, 2)}`,
		`sim.speed          ${fixed(simSnapshot.playerSpeed, 2)}`,
		`sim.warpEngaged    ${String(simSnapshot.gameState.flight.warpEngaged).padStart(8, " ")}`,
		`sim.warpChargeMs   ${fixed(simSnapshot.gameState.flight.warpChargeMs, 1)}`,
		`sim.missiles       ${String(simSnapshot.gameState.flight.missileCount).padStart(8, " ")}`,
		`sim.missileArmed   ${String(simSnapshot.gameState.flight.missileArmed).padStart(8, " ")}`,
		`sim.missileLockMs  ${fixed(simSnapshot.gameState.flight.missileLockTimerMs, 1)}`,
		`sim.ecmEnabled     ${String(simSnapshot.gameState.views.ecmEnabled).padStart(8, " ")}`,
		`sim.ecmActiveMs    ${fixed(simSnapshot.gameState.flight.ecmActiveMs, 1)}`,
		`sim.laserTemp      ${String(simSnapshot.gameState.flow.laserTemperature).padStart(8, " ")}`,
		`sim.safeZone       ${String(simSnapshot.gameState.views.inStationSafeZone).padStart(8, " ")}`,
		`sim.stationDist    ${fixed(simSnapshot.gameState.flight.stationDistance, 1)}`,
		`sim.fuelTenths     ${fixed(simSnapshot.gameState.commander.fuelTenths, 1)}`,
		`sim.docked         ${String(simSnapshot.gameState.views.isDocked).padStart(8, " ")}`,
		`sim.rngState       ${String(simSnapshot.rngState).padStart(8, " ")}`,
		`sim.scenario       ${simSnapshot.scenarioId}`,
		`cfg.variant        ${runtimeConfig.variantId}`,
		`cfg.timing         ${runtimeConfig.timing}`,
		`cfg.timingResolved ${activeTimingProfile.id}`,
		`cfg.stepHz         ${fixed(activeTimingProfile.hz, 1)}`,
		`cfg.stepMs         ${fixed(activeTimingProfile.stepMs, 4)}`,
		`cfg.seed           ${runtimeConfig.seed}`,
		`data.variant       ${runtimeDataContext?.resolvedVariantId ?? "-"}`,
		`data.words         ${String(runtimeDataContext?.dataPack.words.tokenCount ?? 0).padStart(8, " ")}`,
		`data.iantok        ${String(runtimeDataContext?.dataPack.iantok.tokenCount ?? 0).padStart(8, " ")}`,
		`data.ships         ${String(runtimeDataContext?.dataPack.ships.blueprints.length ?? 0).padStart(8, " ")}`,
		`data.wireframes    ${String(wireframeBlueprintMap.size).padStart(8, " ")}`,
		`data.sprites       ${String(
			runtimeDataContext?.dataPack.visuals.sprites.spriteCount ?? 0,
		).padStart(8, " ")}`,
		`data.fontGlyphs    ${String(
			runtimeDataContext?.dataPack.visuals.font.glyphCount ?? 0,
		).padStart(8, " ")}`,
		`data.audioBytes    ${String(
			(runtimeDataContext?.dataPack.audio.comudat.byteLength ?? 0) +
				(runtimeDataContext?.dataPack.audio.theme.byteLength ?? 0),
		).padStart(8, " ")}`,
		`data.token0       ${tokenPreviewText || "-"}`,
		`mission.pages     ${String(missionPreviewPages.length).padStart(8, " ")}`,
		`mission.page1     ${(missionPreviewPages[0] ?? "-").slice(0, 72)}`,
		`audio.master      ${fixed(audioSettings.masterVolume, 2)}`,
		`audio.sfx         ${fixed(audioSettings.sfxVolume, 2)}`,
		`audio.music       ${fixed(audioSettings.musicVolume, 2)}`,
		`audio.muted       ${String(audioSettings.muted).padStart(8, " ")}`,
		`guide.seen        ${String(onboardingAcknowledged).padStart(8, " ")}`,
		`data.padWords      ${String(variantSummary?.wordsPaddingBytes ?? 0).padStart(8, " ")}`,
		`data.iantokTail    ${String(variantSummary?.iantokTrailingPayloadBytes ?? 0).padStart(8, " ")}`,
		`data.error         ${runtimeDataError ?? "-"}`,
		`input.rollAxis     ${inputSnapshot.rollAxis}`,
		`input.pitchAxis    ${inputSnapshot.pitchAxis}`,
		`input.throttle     ${inputSnapshot.throttleAxis}`,
		`input.warpToggle   ${String(inputSnapshot.warpTogglePressed)}`,
		`input.escapePod    ${String(inputSnapshot.escapePodPressed)}`,
		`input.fireLaser    ${String(inputSnapshot.fireLaserPressed)}`,
		`input.missileArm   ${String(inputSnapshot.missileArmTogglePressed)}`,
		`input.missileFire  ${String(inputSnapshot.missileFirePressed)}`,
		`input.ecmToggle    ${String(inputSnapshot.ecmTogglePressed)}`,
		`input.dockAttempt  ${String(inputSnapshot.dockAttemptPressed)}`,
		`input.launch       ${String(inputSnapshot.launchPressed)}`,
		`input.keys         ${inputSnapshot.pressedKeys.join(", ") || "-"}`,
		`bind.fire         ${formatKeyCode(keyBindings.fireLaser).padStart(8, " ")}`,
		`bind.menu         ${formatKeyCode(keyBindings.menuToggle).padStart(8, " ")}`,
		`bind.pause        ${formatKeyCode(keyBindings.pauseToggle).padStart(8, " ")}`,
		`a11y.contrast     ${String(accessibilitySettings.highContrast).padStart(8, " ")}`,
		`a11y.largeText    ${String(accessibilitySettings.largeText).padStart(8, " ")}`,
		`a11y.reducedFlash ${String(accessibilitySettings.reducedFlashing).padStart(8, " ")}`,
		`a11y.leftTouch    ${String(accessibilitySettings.leftHandedTouch).padStart(8, " ")}`,
		`gp.connected      ${String(gamepadSnapshot.connected).padStart(8, " ")}`,
		`gp.rollAxis       ${fixed(gamepadSnapshot.rollAxis, 2)}`,
		`gp.pitchAxis      ${fixed(gamepadSnapshot.pitchAxis, 2)}`,
		`gp.throttle       ${fixed(gamepadSnapshot.throttleAxis, 2)}`,
		`touch.active      ${String(touchSnapshot.active).padStart(8, " ")}`,
		`touch.rollAxis    ${fixed(touchSnapshot.rollAxis, 2)}`,
		`touch.pitchAxis   ${fixed(touchSnapshot.pitchAxis, 2)}`,
		`touch.throttle    ${fixed(touchSnapshot.throttleAxis, 2)}`,
		"",
		"url params:",
		"?scenario=empty&variant=gma85-ntsc&timing=auto&seed=12345&debug=1",
	].join("\n");
}

/**
 * Main browser frame callback:
 * - advances fixed-step simulation,
 * - renders current snapshot,
 * - updates migration debug diagnostics.
 */
function animate(nowMs: number): void {
	// Push latest control state into the deterministic simulation before stepping.
	if (!paused) {
		const mergedControls = mergePilotControls([
			mapKeyboardSnapshotToPilotControls(keyboard.snapshot(), keyBindings),
			mapGamepadSnapshotToPilotControls(gamepad.snapshot()),
			mapTouchSnapshotToPilotControls(touchInput.snapshot()),
		]);
		simulation.setPilotControls(mergedControls);
	}

	const frameNowMs = paused ? (pauseFrameNowMs ?? nowMs) : nowMs;
	const metrics = runner.frame(frameNowMs);
	const snapshot = simulation.snapshot();
	const shouldShowDockedPanel =
		snapshot.gameState.views.isDocked || snapshot.gameState.flow.phase === "docked";
	dockedUiPanel.hidden = !shouldShowDockedPanel;
	if (shouldShowDockedPanel) {
		dockedUiContent.textContent = formatDockedUiContent(activeDockedFlow, snapshot);
	}
	syncMusicTrack(snapshot);

	const elapsedMs = Math.max(0.0001, metrics.elapsedMs);
	perfStats.lastFps = 1000 / elapsedMs;
	perfStats.frameSamples.push(elapsedMs);
	if (perfStats.frameSamples.length > perfStats.sampleLimit) {
		perfStats.frameSamples.shift();
	}
	if (metrics.elapsedMs > activeTimingProfile.stepMs * 1.5) {
		perfStats.overBudgetFrames += 1;
	}
	if (!paused && nowMs - lastAutosaveMs >= AUTOSAVE_INTERVAL_MS) {
		saveSnapshotToLocalStorage(true);
		lastAutosaveMs = nowMs;
	}
	const audioState = deriveAudioCueEdgeState(snapshot);
	const cueDiff = detectAudioCuesFromEdgeStates(
		previousAudioState,
		audioState,
		nowMs,
		lastExplosionCueMs,
	);
	for (const cueId of cueDiff.cues) {
		audio.playSfx(cueId);
	}
	lastExplosionCueMs = cueDiff.nextLastExplosionCueMs;
	previousAudioState = audioState;

	renderer.render(snapshot, metrics);
	updateDebugPanel(nowMs, metrics.elapsedMs, metrics.simulatedSteps, metrics.wasClamped);
	window.requestAnimationFrame(animate);
}

window.requestAnimationFrame(animate);

// Dispose input listeners when the page unloads to keep teardown clean in tests.
window.addEventListener("beforeunload", () => {
	saveSnapshotToLocalStorage(true);
	delete window.__ELITE_DETERMINISM_PROBE__;
	audio.dispose();
	gamepad.dispose();
	touchInput.dispose();
	keyboard.dispose();
});
